Repository VishwamAI/jobcity, pull requests merged in 2024-10, with the labels that each got.

#10 feat(issue-templates): add feature request and bug report templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: HackToberFest

#17 social links added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/landing-page.tsx
Labels: coder, HackToberFest, HackToberFestCompleted

#51 Scroll up button
  frontend/src/App.tsx
  frontend/src/components/ScrollToTopButton.tsx
Labels: HackToberFest, HackToberFestCompleted, hacktoberfest-accepted

#53 get started button working
  frontend/src/landing-page.tsx
Labels: HackToberFest, HackToberFestCompleted, hacktoberfest-accepted

#56 Implementation of the Loader.
  frontend/src/App.tsx
  frontend/src/components/Loader.jsx
  package-lock.json
  package.json
Labels: HackToberFest, HackToberFestCompleted, hacktoberfest-accepted
